name: Node.js CI
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        name: Checkout [main]
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - run: yarn
      - run: yarn build-storybook