name: Deploy
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        name: Checkout [main]
        with:
          fetch-depth: 0
      #- name: create env file
      #  run: |
      #    touch .env
      #    echo GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} >> .env
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - run: yarn
      - run: yarn build-storybook
      - run: yarn deploy